.TH "oggz-known-codecs" "1" 
.SH "NAME" 
oggz-known-codecs \(em List codecs known by this version of Oggz 
 
.SH "SYNOPSIS" 
.PP 
\fBoggz-known-codecs\fR [\-h  | \-\-help ]  [\-v  | \-\-version ]  
.SH "Description" 
.PP 
\fBoggz-known-codecs\fR lists the names of codecs for which oggz can 
interpret timestamps and report general information. These codec names are 
valid arguments to the \fB-c\fR, \fB\-\-content-type\fR
arguments to other \fBoggz\fR commands. 
 
.SH "Options" 
.PP 
\fBoggz-known-codecs\fR accepts the following options: 
 
.SS "Miscellaneous options" 
.IP "\-h, \-\-help" 10 
Display usage information and exit. 
.IP "\-v, \-\-version" 10 
Output version information and exit. 
.SH "AUTHOR" 
.PP 
Conrad Parker        July  9, 2008;      
.SH "COPYRIGHT" 
.PP 
Copyright \(co 2008 Annodex Association 
 
.SH "SEE ALSO" 
.PP 
\fBoggz\fP\fB(1)\fP, 
\fBoggz-info\fP\fB(1)\fP, 
\fBhogg\fP\fB(1)\fP      
.\" created by instant / docbook-to-man, Mon 23 Feb 2009, 12:35 
